# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  bump-type:
    description: 'the type of bumpversion excution major.minor.patch '
    required: true
    default: 'patch'
outputs:
  new_version:
    description: 'the new version after the bump version .'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bump-type }}
