# action.yml
name: 'Github Action for Bumpversion'
description: 'bumpversion action for bumping the version of the project .'
author: 'rachid ouhammou'
inputs:
  bump-type:
    description: 'the type of the bump version .'
    required: true
    default: 'patch'
    options: ['major', 'minor', 'patch']
  
  ssh-private-key:
    description: 'the ssh private key to use for the git push .'
    required: true
    secret: true
  
  branch:
    description: 'the branch to push the changes to .'
    required: true
    default: 'main'
  
  github-token:
    description: 'the github'
    required: true
    secret: true
  release-title:
    description: 'the title of the release .'
    required: false
    default: ''
  generate-notes:
    description: 'generate notes for the release .'
    required: false
    default: true

outputs:
  new-version:
    description: 'the new version after the bump version .'
    value: ${{ steps.bump.outputs.new_version }}
  old-version:
    description: 'the old version before the bump version .'
    value: ${{ steps.bump.outputs.old_version }}
runs:
  using: 'composite'
  steps:

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Upgrade pip & Install Poetry.
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install bumpver
      shell: bash

    - name: Bump version
      id: bump
      run: |
        echo "old_version=$(poetry version -s)" >> $GITHUB_OUTPUT
        echo "old_version=$(poetry version -s)" >> $GITHUB_ENV
        poetry run bumpver update --${{ inputs.bump-type }}
        echo "new_version=$(poetry version -s)" >> $GITHUB_OUTPUT
        echo "new_version=$(poetry version -s)" >> $GITHUB_ENV
      shell: bash
    
    - name: Set outputs
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
  
    - name: Commit Files
      run: |
        git config --global user.name "GitHub Actions [Bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Bump version from ${{ env.old_version }} ⟶ ${{ env.new_version }}"
      shell: bash
      
    - name: Push Changes via SSH
      run: |
        git push git@github.com:$GITHUB_REPOSITORY.git ${{ inputs.branch }}
      shell: bash
    
    - name: Create release with generated notes
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        tag: "v${{env.new_version}}"
        title: ${{ inputs.release-title }}
      if : ${{ inputs.generate-notes }}
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${title} v${tag#v}" \
            --generate-notes
      shell: bash
    
    - name: Create release without generated notes
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        tag: "v${{env.new_version}}"
        title: ${{ inputs.release-title }}
      if : ${{ !inputs.generate-notes }}
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${title} v${tag#v}"
      shell: bash
    
branding:
  icon: 'chevrons-up'
  color: 'blue'
