[bumpver]
current_version = "1.2.0"
version_pattern = "MAJOR.MINOR.PATCH"
tag = true
commit=true
[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"$',
]
"README.md" = [
    'bumpversion-action@v{version}$',
]
