[bumpver]
current_version = "0.1.26"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"$',
]
"__init__.py" = [
    "^__version__ = '{version}'$",
]