[bumpver]
current_version = "1.1.0"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"$',
]
"README.md" = [
    'bumpversion-action@v{version}$',
]
