[tool.poetry]
name = "pyxo"
version = "0.1.14"
description = ""
authors = ["ouhammmourachid <rachidouhammou21@gmail.com>"]
license = "MIT"
readme = "README.md"

[bumpver]
current_version = "0.1.14"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"$',
]



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"