name: Bumpversion Action

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test-bumpversion-action:
    runs-on: ubuntu-latest
    name: A job to test the bumpversion action
    steps:
      - name: checkout action
        uses: actions/checkout@v4
      - name: bumpversion-action
        id: bumpversion-action
        uses: ./
        with:
          bump-type: 'patch'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          generate-notes: false
      - name: get the version output
        run: |
          echo "new_version: ${{ steps.bumpversion-action.outputs.new-version }}"
          echo "old_version: ${{ steps.bumpversion-action.outputs.old-version }}"

