name: Bumpversion Action

on:
  push:
    branches:
      - test

permissions:
  contents: write
  pull-requests: write

jobs:
  test-bumpversion-action:
    runs-on: ubuntu-latest
    name: A job to test the bumpversion action
    steps:
      - name: checkout action
        uses: actions/checkout@v4
      - name: bumpversion-action
        uses: ./
        with:
          bump-type: 'patch'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: 'test'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: get the version output
        run: |
          echo "new_version: ${{ steps.bumpversion-action.outputs.new_version }}"
          echo "old_version: ${{ steps.bumpversion-action.outputs.old_version }}"

